
###
GET http://localhost:3000/api/tiposIngrediente

###

GET http://localhost:3000/api/tiposIngrediente/001

###

POST http://localhost:3000/api/tiposIngrediente
Content-Type: application/json

{
  "codigo": "2",
  "descripcion": "Fruta"
}